apiVersion: apps/v1
kind: Deployment
metadata:
  name: "offers"
  namespace: ms
  labels:
    app: "offers"
spec:
  selector:
    matchLabels:
      app: "offers"
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "offers"
    spec:
      containers:
      - name: "offers"
        image: kingsleyche67/offers
        ports:
        - containerPort: 1001
          name: "offers"

---
apiVersion: v1
kind: Service
metadata:
  name: "offers"
  namespace: ms
spec:
  selector:
    app: "offers"
  type: NodePort
  ports:
  - name: "offers"
    port: 1001
    targetPort: 1001


